name 'nagios'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'mit'
description 'Installs/Configures nagios'
long_description 'Installs/Configures nagios'
version '0.1.1'

depends 'selinux', '~> 0.9'
depends 'chef-vault', '~> 1.3'
depends 'mysql', '~> 6.1'
depends 'php', '~> 1.7'
depends 'php-fpm', '~> 0.7.4'
depends 'firewalld', '~> 1.1'
