name 'nagios'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'mit'
description 'Installs/Configures nagios'
long_description 'Installs/Configures nagios'
version '0.1.0'
